# Generated by Django 2.2 on 2020-07-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0002_auto_20200715_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
